##
## Build
##

FROM golang:1.19-buster AS build

WORKDIR /app

COPY go.mod .
COPY go.sum .
RUN go mod download

COPY *.go ./
COPY /root ./root

RUN go build -o /http-server

##
## Deploy
##

FROM gcr.io/distroless/base-debian10

WORKDIR /

COPY --from=build /http-server /http-server

EXPOSE 8080

USER nonroot:nonroot

ENTRYPOINT ["./http-server", "8080"]
